#!/usr/bin/env bash

APP="bot" # name of your release

BUILD_HOST="136.243.10.43" # host where to build the release
BUILD_USER="bot" # local user at build host
BUILD_AT="/tmp/erlang/bot/builds" # build directory on build host

LINK_VM_ARGS=/home/bot/bot/running-config/vm.args
PRODUCTION_HOSTS="136.243.10.43" # deploy / production hosts separated by space
PRODUCTION_USER="bot" # local user at deploy hosts
DELIVER_TO="/home/bot" # deploy directory on production hosts
